-- AlterEnum
ALTER TYPE "AutomationTrigger" ADD VALUE 'CHALLENGE_ENROLLED';
ALTER TYPE "AutomationTrigger" ADD VALUE 'CHALLENGE_COMPLETED';
ALTER TYPE "AutomationTrigger" ADD VALUE 'PATHWAY_COMPLETED';
ALTER TYPE "AutomationTrigger" ADD VALUE 'DAILY_CHECKIN_STREAK';
ALTER TYPE "AutomationTrigger" ADD VALUE 'RECOGNITION_RECEIVED';
ALTER TYPE "AutomationTrigger" ADD VALUE 'BRAIN_BUILDER_MILESTONE';
